### ISSUE TITLE
signature to string

### ISSUE THREAD

**Issue by morrning** [starkbank/ecdsa-php#10]
how can i convert signature to string for transfer over webservice

**Comment by cdottori-stark** [comment]
Hello,

Ideally this should be done using the toBase64 method of the signature object:

```php
$signature = EllipticCurve\Ecdsa::sign($message, $privateKey);
$base64String = $signature1->toBase64();
```

Then you can reverse rebuild the object from the string using the fromBase64 method:
```php
$signature = EllipticCurve\Signature::fromBase64($base64String);
```
