### ISSUE TITLE
How to echo R and S values

### ISSUE THREAD

**Issue by smartkodian** [starkbank/ecdsa-php#12]
Hi,
Thanks for great Library, but I am not getting how to get the R and S values?

**Comment by leandro-stark** [comment]
Hello, SmartKodian! How are you ?

Unfortunately, our PHP and Ruby ECDSAs are only thin OpenSSL wrappers right now, unlike the other released ECDSAs that have native implementations. Therefore, it’s still not able to easily display the R and S values.

We intend to release the native PHP and Ruby ECDSAs as well, however. Once they’re released, it will be easy to retrieve those values with little effort, like it’s done with the other ECDSAs.

Best,
