### ISSUE TITLE
AdMob SSV error:0906D06C

### ISSUE THREAD

**Issue by Obnotname** [starkbank/ecdsa-php#4]
I would like to use your library for the server side verification of AdMob

`$publicKeyPem = "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+nzvoGqvDeB9+SzE6igTl7TyK4JB\nbglwir9oTcQta8NuG26ZpZFxt+F2NDk7asTE6/2Yc8i1ATcGIqtuS5hv0Q==\n-----END PUBLIC KEY-----";
$signatureDerStr = "MEQCIB5DcAc4SO-gjbEFu-ZYfG_LGkX-tp4Nb0DIMjh71SQeAiBAwXcveOUVDcmQ4Royc1Fxbzd13n7gc3AN4QXbPsdvSw";
$message = "some_message";

$signatureDer = base64_encode($signatureDerStr);
$message = urldecode($message);
$msgHash = hash('sha256', $message);

$publicKey = EllipticCurve\PublicKey::fromPem($publicKeyPem);
$signature = EllipticCurve\Signature::fromDer($signatureDer);

    echo "\n" . EllipticCurve\Ecdsa::verify($msgHash, $signature, $publicKey);`

Unfortunetly the verify method gives me this error:

**error:0906D06C:PEM routines:PEM_read_bio:no start line**

**Comment by cdottori-stark** [comment]
Hi Obnotname,

There a few issues with the usage of the library in your code, here is the corrected example:

`
$publicKeyPem = "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+nzvoGqvDeB9+SzE6igTl7TyK4JB\nbglwir9oTcQta8NuG26ZpZFxt+F2NDk7asTE6/2Yc8i1ATcGIqtuS5hv0Q==\n-----END PUBLIC KEY-----";
$signatureBase64 = "MEQCIB5DcAc4SO-gjbEFu-ZYfG_LGkX-tp4Nb0DIMjh71SQeAiBAwXcveOUVDcmQ4Royc1Fxbzd13n7gc3AN4QXbPsdvSw";
$message = "some_message";

$publicKey = EllipticCurve\PublicKey::fromPem($publicKeyPem);
$signature = EllipticCurve\Signature::fromBase64($signatureBase64);
echo "\n" . EllipticCurve\Ecdsa::verify($message, $signature, $publicKey);
`

Hope you find it useful!

**Comment by Obnotname** [comment]
Hi 👋

I am now using a Python library, however THANK YOU very much for replying to this quite old post of me, I will look into it in a few days, would be really nice to have this SSV in full php finally. 

On top, I was actually planning to look again into writing the check in php instead of having to this workaround of calling an extra python file etc. 

Once again thank you 👍

**Comment by cdottori-stark** [comment]
No problem! And sorry about the huge delay on our reply. In case you're interested, we actually implemented the same ECDSA interface in [several languages](https://github.com/starkbank?q=ecdsa), including Python.

**Comment by Obnotname** [comment]
Ah no problem :) Great to know that 👍

**Comment by Obnotname** [comment]
Hi, it's me again.

I have now tried your example, however it still returns false on verification

**Comment by cdottori-stark** [comment]
That's because either the public key or the signature do not match the provided message. Here is an example that returns true on verification:

`
<?php
require_once "vendor/autoload.php";

$message = "some_message";

$privateKey = new EllipticCurve\PrivateKey();
$publicKeyPem = $privateKey->publicKey()->toPem();
$signatureBase64 = EllipticCurve\Ecdsa::sign($message, $privateKey)->toBase64();
echo "public key: " . $publicKeyPem;
echo "signature: " . $signatureBase64;

$publicKey = EllipticCurve\PublicKey::fromPem($publicKeyPem);
$signature = EllipticCurve\Signature::fromBase64($signatureBase64);
if (EllipticCurve\Ecdsa::verify($message, $signature, $publicKey)) {
  echo "\nMessage is valid\n";
} else {
  echo "\nMessage is invalid\n";
}
`

**Comment by Obnotname** [comment]
Hi again, 

thanks for your reply, I've tested your code and it worked, however with my strings it still says invalid.
Within the working Python-Code I've found those lines:

prepared_key = VerifyingKey.from_pem(public_key)

    prepared_msg = (urllib.parse.unquote(content)).encode('utf-8')
    prepared_sig = base64.urlsafe_b64decode(signature + '===')

    try:
        result = prepared_key.verify(
            prepared_sig,
            prepared_msg,
            hashfunc=hashlib.sha256,
            sigdecode=sigdecode_der,
        )

        if result:
            print("Result is true", end='')

    except BadSignatureError as e:
        print("NULL")

**I am a total noob within the cryptographic space :/ In case you understand this quite easily, I would be really happy in case you can check this again & tell me how it works, in case it works at all with this library**


These are my plain strings, as I receive them. There is nothing done to them yet:

publicKey: 
-----BEGIN PUBLIC KEY-----
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEGpRlChCiilDu5el58I5Vp6YEmyuvVgzq
Z6VzxPayVUj95fgucEt2SZMVSCO5NE5ngErDC7W/BGROltpc4sMe6w==
-----END PUBLIC KEY-----


signature: 
MEYCIQDGj4F6TW79PT3lA6dHSNdya-OgVZuyHoWt2n4ZlFGvawIhAOftl2zIq7Ki2HQujVOzWAsia_uO4ojCtLJM4ZGvpk94 

Message:
 ad_network=5450213213286189855&ad_unit=3430014594&reward_amount=7&reward_item=Reward&timestamp=1593684944978&transaction_id=0cb3fbbe45d94d991763e98fe3668d44&user_id=erik.boscher%40web.de


Thank you very much in advance!

**Comment by cdottori-stark** [comment]
I am not familiar with the lib you're using. The same example would look like this using our [python lib](https://github.com/starkbank/ecdsa-python):

```python
from ellipticcurve.publicKey import PublicKey
from ellipticcurve.ecdsa import Ecdsa
from ellipticcurve.signature import Signature
import base64
import urllib


publicKey = """
-----BEGIN PUBLIC KEY-----
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEGpRlChCiilDu5el58I5Vp6YEmyuvVgzq
Z6VzxPayVUj95fgucEt2SZMVSCO5NE5ngErDC7W/BGROltpc4sMe6w==
-----END PUBLIC KEY-----"""
signature = "MEYCIQDGj4F6TW79PT3lA6dHSNdya-OgVZuyHoWt2n4ZlFGvawIhAOftl2zIq7Ki2HQujVOzWAsia_uO4ojCtLJM4ZGvpk94"
message = "ad_network=5450213213286189855&ad_unit=3430014594&reward_amount=7&reward_item=Reward&timestamp=1593684944978&transaction_id=0cb3fbbe45d94d991763e98fe3668d44&user_id=erik.boscher%40web.de"

prepared_msg = urllib.parse.unquote(message)
prepared_key = PublicKey.fromPem(publicKey)
prepared_sig = Signature.fromDer(base64.urlsafe_b64decode(signature + "==="))

result = Ecdsa.verify(
    message=prepared_msg,
    signature=prepared_sig,
    publicKey=prepared_key,
)

print(result)
```

Which, as you noted, prints False.

My only guess is that the code is not correctly rebuilding the prepared_msg with the current parsing. If any message bytes are out of place during verification, the signature and public key won't verify it. If possible, try to understand exactly how the message was encoded for transmission, as the process has to be precisely reversed for this verification to work.

**Comment by KuLi** [comment]
The signature is base64 encoded websafe! You must convert the signature before.

```
// credits to https://www.php.net/manual/de/function.base64-encode.php#103849
function base64url_decode($data) {

    return base64_decode(str_pad(strtr($data, '-_', '+/'), strlen($data) % 4, '=', STR_PAD_RIGHT));
}
```

After that you can use it like this
```
$signature = \EllipticCurve\Signature::fromDer(base64url_decode("MEYCIQCQfAX-JkarkUSduywcSAm00wN0UfhUmXQvaZSci4chVgIhAMbl6ZXX_dKl5BWYhLLWzlsUrgr_ptpxEJvHsZJCLL2e"));
```
